### PR TITLE
Update fermium bindings, add API to access DPI

### PR DESCRIPTION
**Pull request by Bombfuse**

### CODE REVIEW

**Comment by Lokathor** [comment]
Hate to pull the rug out from under you, but you should switch up to the fermium i finalized today: 200.12.0

Which _should_ be similar, but there will probably be some build errors here and there to fix up.

**Comment by Lokathor** [comment]
Actually, `200.12` without the .0 on the end should be enough

**Comment by Bombfuse** [comment]
Will update and re:PR

**Comment by Lokathor** [comment]
If you just push changes to your existing branch Github will see the changes and make them part of this PR here.

**Comment by Lokathor** [comment]
Looks like the appveyor script needs some fixing too still

**Comment by Lokathor** [comment]
All set for a merge?

**Comment by Bombfuse** [comment]
Yah it should be good to go

**Pull request merged**
